#!/usr/bin/env node
// Turn the vendored craft corpus into a TypeScript module the Netlify function
// can import. esbuild bundles the function; it cannot read .md files from the
// deployed bundle, so the text is baked in as string constants.
//
//   npm run corpus:build   (also runs as the first step of `npm run build`)
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const corpusDir = path.join(root, "netlify/functions/lib/corpus");
const outPath = path.join(root, "netlify/functions/lib/corpus.generated.ts");

const manifest = JSON.parse(fs.readFileSync(path.join(corpusDir, "manifest.json"), "utf8"));
const preamble = fs.readFileSync(path.join(corpusDir, "PREAMBLE.md"), "utf8");
const wanted = [...new Set([...manifest.core, ...Object.values(manifest.ops).flat()])].sort();

const files = {};
const hash = crypto.createHash("sha256");
hash.update(preamble);
for (const rel of wanted) {
  const text = fs.readFileSync(path.join(corpusDir, rel), "utf8");
  files[rel] = text;
  hash.update(rel).update("\0").update(text).update("\0");
}
const digest = hash.digest("hex").slice(0, 16);

const out = `// GENERATED by scripts/corpus-build.mjs — do not edit. Source: netlify/functions/lib/corpus/.
// Re-run \`npm run corpus:build\` after touching manifest.json, PREAMBLE.md or a vendored file;
// \`npm run corpus:sync\` re-vendors from ~/.claude/skills first.
/* eslint-disable */

export const CORPUS_MANIFEST = ${JSON.stringify(
  { source: manifest.source, core: manifest.core, ops: manifest.ops },
  null,
  2,
)} as const;

/** sha256 (first 16 hex) over PREAMBLE + every vendored file — the drift check compares it. */
export const CORPUS_DIGEST = ${JSON.stringify(digest)};

export const CORPUS_PREAMBLE = ${JSON.stringify(preamble)};

export const CORPUS_FILES: Record<string, string> = {
${wanted.map((rel) => `  ${JSON.stringify(rel)}: ${JSON.stringify(files[rel])},`).join("\n")}
};
`;
fs.writeFileSync(outPath, out);
const kb = Math.round(Buffer.byteLength(out) / 1024);
console.log(`corpus-build: ${wanted.length} files, ${kb} KB → ${path.relative(root, outPath)} (digest ${digest})`);
